wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.4
    start_time: 1676210736.609457
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.7.4
      5: 0.13.10
      8:
      - 2
      - 5
